Add exclusions for Chromecast devices
leikoilja/ha-google-home pull request #212
Opened 2021-04-15 21:51 UTC by stboch

Since chromecast devices do not currently support the google home api, exclude these devices from api calls in the same manner as devices missing IP's or auth tokens.

PR to address issue #211

2021-04-15 22:05 UTC, KapJI requested changes
Chromecast devices do support Google Home local API. They don't support alarms. We still want to create `device` sensor for them.

The idea is that we don't want to have explicit list of supported devices. If device responds to alarms endpoint, it's supported otherwise it's not. Currently we keep polling unsupported devices and this can be improved. Like stop polling devices which returned 404.

I'm not sure what's your concern here. These log messages you have are on debug level anyway. I'm not convinced we need this.

2021-04-15 22:41 UTC, stboch commented
Really just trying to cut back on all the erroneous calls to stuff that will fail i have about 12 chromecasts on my network just a lot of traffic that will fail. 
Either way my rush realized that using the other method I moved to higher in the calls wasn't the best. would be better implemented in the collect_data_from_endpoints as it will still populate the other components in HA just lack the other entities.

2021-04-15 22:43 UTC, closed without merging

2021-04-15 22:47 UTC, KapJI commented
My calculations that each request is under 1 KB. With polling interval of 10 s, you have ~1 KB/s of erroneous traffic in your network. Shouldn't be a big deal.

2021-04-16 07:13 UTC, leikoilja commented
@KapJI i still think we need to come up with a better way to sort of entities as users ask. As i mentioned somewhere else, we can try doing requests to `eureka` endpoint and fetching device capabilities and based on that filter the ones that don't support google assistant. I tried playing with that a bit the other day and think it could be doable

2021-04-16 09:11 UTC, KapJI commented
@leikoilja even without eureka info chromecasts return 404 on alarms endpoint. We can use that to filter them out without creating an explicit model list.

2021-04-16 09:13 UTC, leikoilja commented
Either that or reverting back to the config options where one can add custom filtering wildcard(s)

2021-04-18 09:40 UTC, DurgNomis-drol commented
I agree with @leikoilja and @stboch I have an android TV and it constantly makes request to it for alarms and timers, and Do Not Disturb which is not supported and we should find a way to eliminated unnecessary request, even if they are small and fast. 

As far as i understand, we can get determine if the devices is compatible through the eureka info endpoint.

2021-04-18 10:42 UTC, KapJI commented
I think just adding device to unsopported list if it returns 404 is the simplest and the most robust way to do that. 🙂

2021-04-18 10:45 UTC, DurgNomis-drol commented
But what if a device is offline? Then it will return 404, but still be compatible.

2021-04-18 10:50 UTC, KapJI commented
Offline revice can't return 404. It will be unreachable.

2021-04-18 11:01 UTC, DurgNomis-drol commented
Right, i think i understand now.

Or we can just check it against this information returned from `eureka_info` endpoint:

```yaml
"device_info": {
  "capabilities": {
    "aogh_supported": true,
    "assistant_supported": true,
    "audio_hdr_supported": false,
    "audio_surround_mode_supported": false,
    "ble_supported": true,
    "bluetooth_audio_sink_supported": true,
    "bluetooth_audio_source_supported": true,
    "bluetooth_supported": true,
    "cloudcast_supported": true,
    "content_filters_supported": true,
    "display_supported": false,
    "fdr_supported": false,
    "hdmi_prefer_50hz_supported": false,
    "hdmi_prefer_high_fps_supported": false,
    "hotspot_supported": true,
    "https_setup_supported": true,
    "input_management_supported": true,
    "keep_hotspot_until_connected_supported": true,
    "multi_user_supported": true,
    "multichannel_group_supported": true,
    "multizone_supported": true,
    "night_mode_supported": true,
    "night_mode_supported_v2": true,
    "opencast_supported": false,
    "preview_channel_supported": true,
    "reboot_supported": true,
    "remote_ducking_supported": true,
    "separate_tts_volume_supported": true,
    "setup_supported": true,
    "sleep_mode_supported": true,
    "stats_supported": true,
    "system_sound_effects_supported": false,
    "user_eq_supported": true,
    "wifi_auto_save_supported": true,
    "wifi_regulatory_domain_locked": true,
    "wifi_supported": true
    },
}
```

I believe that `assistant_supported` is the one we are looking for. 😃

2021-04-18 11:07 UTC, KapJI commented
Yeah, checking for 404 or querying `eureka_info`, both should work. My idea is checking 404 is simpler and more straightforward as you don't need to query another endpoint.

2021-04-18 11:17 UTC, DurgNomis-drol commented
Actually even if the devices returns a `200` for `eureka_info`, there is no guaranty that the device supports alarms or timers, we still would need to check `assistant_supported`. This can also come in handy in the future where we can check what other features is supported. 

The check should probably be a combination of both like this:

1. Request `eureka_info` if `404` return device **not** compatible. Else continue check.
2. Check if `assistant_supported` is true, return device is compatible. If false return device is **not** compatible.

2021-04-18 11:18 UTC, KapJI commented
I mean 404 on `alarms` endpoint, not `eureka_info`.

2021-04-18 11:29 UTC, DurgNomis-drol commented
Mine is more explicit, which is very pythonic. 😄

2021-04-18 11:34 UTC, stboch commented
using the array of supported features is a better result and is what we do on the surbaru side, we map the returned feature codes a car has to the APIs that we support to prevent this calls. Now that's to prevent calls to a third party site and not get caught being naughty to the api but the same effect locally is still a good choice. If all local devices still respond to eureka_info and we can differentiate the APIs based on the supported status then I think this is the right way to go.

2021-04-18 11:40 UTC, DurgNomis-drol commented
I have created a separate issue to track that feature. 😃 Lets keep all further discussions about over there.