Added Catalan translations
leikoilja/ha-google-home pull request #249
Opened 2021-06-06 10:54 UTC by ArnyminerZ

Added the Catalan language into the `translations` directory.
Also added the localization label for all PRs related to translations.

2021-06-06 11:05 UTC, ArnyminerZ commented
Still missing services localization, and maybe sensors, but still finding out how to do it.

2021-06-07 12:10 UTC, KapJI requested changes

2021-06-07 12:10 UTC, KapJI commented on .github/labels.yml
> +- name: localization
Then you need to assign some section in release drafter for it. Probably just create the new one. Worth splitting as a separate PR.

2021-06-07 12:10 UTC, KapJI commented on custom_components/google_home/types.py
> +class DoNotDisturbAttributes(TypedDict):
This doesn't look related to translation, please submit a separate PR for it.

2021-06-07 12:10 UTC, KapJI commented on custom_components/google_home/const.py
> +
These are not valid values. List of supported device classes for `sensor` platform: https://www.home-assistant.io/integrations/sensor/

2021-06-07 13:47 UTC, leikoilja reviewed
Great initiative to implement translations, thank you 🙌  
Once it's merged i ll add Russian language as well 🚀 
Let's split the proposed changes into 3 separate PRs and clean up a little, this is really important because it makes it much easier to review and keeps git history much better structured and organised. 
We can have:
- 1 PR for adding new labeler and draft releaser section
- 1 PR for Catalan translations
- 1 PR for refactoring (like adding new classes and attributes)

2021-06-08 16:32 UTC, KapJI approved these changes
Thanks! Let's add more translations 😊

2021-06-08 16:34 UTC, merged