Add README.md notice about update interval changes and issues
leikoilja/ha-google-home pull request #303
Opened 2021-08-11 13:28 UTC by DurgNomis-drol

Please give feedback 😃

2021-08-11 13:32 UTC, DurgNomis-drol commented
Also this means that people need to update their translations to include the new string. 😃

2021-08-11 16:27 UTC, KapJI requested changes

2021-08-11 16:27 UTC, KapJI commented on README.md
> +## IMPORTANT!!
```suggestion
## IMPORTANT
```

2021-08-11 16:27 UTC, KapJI commented on README.md
> +experincing devices timing out when trying to get data from them.
```suggestion
This is due to [#202](https://github.com/leikoilja/ha-google-home/issues/202). Some people are
experiencing devices timing out when trying to fetch data from them.
```

2021-08-11 16:27 UTC, KapJI commented on README.md
> +page. Default is 180 seconds. Change this at your own risk!. If your devices are timing out,
```suggestion
page. Default is 180 seconds. Change this at your own risk! If your devices are timing out,
```

2021-08-11 16:27 UTC, KapJI commented on README.md
> +It is possible to manually change the update interval by pressing the `configure` button on the integration
```suggestion
You can manually change the update interval by pressing the `configure` button on the integration
```

2021-08-11 16:28 UTC, KapJI commented
> Also this means that people need to update their translations to include the new string. 😃

Can you update them? Just using Google Translate should be sufficient.

2021-08-11 16:37 UTC, DurgNomis-drol commented
@KapJI Wouldn't that be better for separate PR?

2021-08-11 16:48 UTC, KapJI commented
I don't mind either way.

2021-08-11 16:48 UTC, KapJI approved these changes

2021-08-11 16:56 UTC, merged

2021-08-12 09:08 UTC, leikoilja commented
Awesome , thanks guys! 🚀