Add support for entity_categories
leikoilja/ha-google-home pull request #398
Opened 2021-11-21 17:20 UTC by DurgNomis-drol

Minor refactor to enable support for `entity_categories`. https://developers.home-assistant.io/blog/2021/10/26/config-entity

This moves the required Home Assistant version to `2021.11`

2021-11-22 22:40 UTC, ArnyminerZ approved these changes
For me it now looks much cleaner now as well 🚀

2021-11-23 09:30 UTC, leikoilja requested changes
That looks amazing! Thanks for some great refactoring 🚀 

Can you please bump min version of `homeassistant` in `hacs.json` file as well? :)

2021-11-23 17:34 UTC, DurgNomis-drol commented
@leikoilja Good catch!

2021-11-24 07:49 UTC, leikoilja approved these changes
Awesome, thanks @DurgNomis-drol 🚀

2021-11-24 07:49 UTC, merged