Added password length check
leikoilja/ha-google-home pull request #506
Opened 2022-04-04 10:47 UTC by ArnyminerZ

Should fix #430, not yet tested.

2022-04-06 06:15 UTC, leikoilja reviewed
This is awesome!
However, i would argue that we should move this validation to `glocaltokens` package, since it is it's job to take in input parameters and return auth tokens. It is also probably `glocaltoken` that is freezing out if too long password is given. 
We can move this validation to `glocaltokens` and raise an error during authentication. Here, we can capture the error and show the UI error message. That approach will also allow us to unittest lengthy passwords in `glocaltokens`. What do you think?

2022-04-06 14:20 UTC, ArnyminerZ commented
@leikoilja I've opened leikoilja/glocaltokens#229 for this

2022-04-07 06:36 UTC, leikoilja requested changes

2022-04-07 06:36 UTC, leikoilja commented on custom_components/google_home/config_flow.py
> +            else:
Just a matter of coding preference but it's nice to have a first block of `if` being "the longest". 
Like:
```python
from .const import MAX_PASSWORD_LENGTH
...
if len(password) < MAX_PASSWORD_LENGTH:
  ... # all the major logic
else:
  self._errors["base"] = "pass-len"
```
but it's purely up to the way you like it :) 
However, please move out the static `100` into a `const` for easier re-usability and style :)

2022-04-07 13:06 UTC, leikoilja approved these changes
This is awesome! Thanks @ArnyminerZ for the implementation 💥 
Can you please make sure the linting checks passes and merge in when happy with it?

2022-04-08 11:28 UTC, merged