Create pl.json
leikoilja/ha-google-home pull request #565
Opened 2022-07-03 09:14 UTC by LukaszP2

polish translation

2022-07-03 18:15 UTC, KapJI requested changes
Please update README.md.

There is also #563, please a look if some wording is better there.

2022-07-03 18:15 UTC, KapJI commented on custom_components/google_home/translations/pl.json
> +        Jeśli nie chcesz, zwykłe hasło do konta Google powinno działać.",
JSON can't contain a new line.

2022-07-04 06:20 UTC, LukaszP2 commented on custom_components/google_home/translations/pl.json
> +        Jeśli nie chcesz, zwykłe hasło do konta Google powinno działać.",
It should works ;)

2022-07-11 11:16 UTC, KapJI commented
No response from the author, closing in favour of #563.

2022-07-11 11:16 UTC, closed without merging