Allow Refreshing Devices During Deletes or Manually
leikoilja/ha-google-home pull request #806
Opened 2023-12-07 07:38 UTC by jmillnik

- Add an optional `force_refresh` parameter to `delete_timers` and `delete_alarms`
- Add a `refresh_devices` service to allow manual refreshes

Both options invoke `async_request_refresh` on the coordinator and therefore restart the refresh timer to prevent over-requesting devices. They provide a reasonable (and optional) method to immediately update devices when deleted, or to allow users to refresh timers/alarms.

2023-12-07 14:33 UTC, KapJI commented
> Add an optional `force_refresh` parameter to `delete_timers` and `delete_alarms`

Do we really need this to be configurable? I'm ok with doing it by default, seems reasonable to me.

2023-12-07 15:24 UTC, jmillnik commented
> Yeah, makes sense. Let's default to true and name it `skip_refresh` then. Also it will be great if you can add translations to other languages using some online service.

Makes sense will knock this out after work and get it all cleaned up. Just fixed my pre-commit to fix the linting. Running on a windows laptop atm :(

2023-12-07 15:39 UTC, KapJI commented on custom_components/google_home/sensor.py
> +        {  # types: ignore[dict]
This one shouldn't be needed.
```suggestion
        {
```

2023-12-08 11:53 UTC, KapJI requested changes

2023-12-08 11:53 UTC, KapJI commented on README.md
> +| `force_refresh` | `true`                                       | Boolean to force refreshing Google Home devices. |
Please update docs as well.

2023-12-08 11:53 UTC, KapJI commented on custom_components/google_home/services.yaml
> +      default: true
I meant default true for `force_refresh`. For `skip_refresh` it should be false.

2023-12-11 11:39 UTC, KapJI approved these changes
Thanks!

2023-12-11 11:39 UTC, merged