Closes #78
leikoilja/ha-google-home pull request #89
Opened 2021-03-11 21:27 UTC by DurgNomis-drol

2021-03-11 21:31 UTC, KapJI commented
Please run `poetry run pre-commit run --all-files` to format everything :)

2021-03-11 21:31 UTC, KapJI commented on README.md
> +- [Google Home timers card](https://github.com/DurgNomis-drol/google_home_timers_card) by [@DurgNomis-drol](https://github.com/DurgNomis-drol)poetry intall
This shouldn't be here.

2021-03-11 21:41 UTC, DurgNomis-drol commented
@KapJI sorry, I have some problems on Windows. But i think i got it now

2021-03-11 21:45 UTC, DurgNomis-drol commented
Other then that, poetry is very nice! Thanks for introducing it to us 😄

2021-03-11 21:54 UTC, KapJI requested changes

2021-03-11 21:54 UTC, KapJI commented on custom_components/google_home/api.py
> +    """ API client"""
Sorry 🙂
```suggestion
    """API client"""
```

2021-03-11 21:56 UTC, KapJI approved these changes
Looks great! Thank you 🎉

2021-03-11 21:57 UTC, merged

2021-03-12 06:59 UTC, leikoilja commented
Awesome stuff, thank you both! 🎉